trigger: none
pr: none

stages:
- stage: deploy
  jobs:
  - job: 'Execute_Test_Automation'
  - deployment: Test_Automation
    displayName: Test_Automation
    timeoutInMinutes: 0
    # creates an environment if it doesn't exist
    environment: 
      name: 'UFT Hosts'
      resourceName: PUE01VM1493
      resourceType: virtualMachine
    strategy:
     runOnce:
       deploy:
         steps: 
           - task: RunFromALMTask@5
             inputs:
               varAlmserv: 'http://15.119.127.231:8080/qcbin'
               varClientID: apikey-ecjkfmiskfpicfqbnjeo
               varApiKeySecret: ddpinmcmjkaecghj 
               varDomain: 'KOSTA'
               varProject: '404'
               varTestsets: 'Root\TS 1\S1'
               runMode: 'runRemotely'
               testingToolHost: 'PUE01VM1493'
